[package]
name = "svelte-on-rust"
version = "0.2.0"
authors = ["Sachin Bhutani <sachin1705@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
rocket = { version = "=0.5.0-rc.3", features = ["secrets","json"] }
rocket_dyn_templates = { version = "=0.1.0-rc.3", features = ["tera"] }
serde = { version ="1.0.159", features = ["derive"] }
sha2 = "0.10.6"
